import { useEffect, useState } from "react";

// Purely informational — codes are generated by the user's authenticator
// app, not here. This just visualizes the standard 30-second TOTP window
// so it's clear why a code stops working if you wait too long to type it.
function CodeCountdownRing({ period = 30 }) {
    const [secondsLeft, setSecondsLeft] = useState(period - (Math.floor(Date.now() / 1000) % period));

    useEffect(() => {
        const tick = () => setSecondsLeft(period - (Math.floor(Date.now() / 1000) % period));
        const interval = setInterval(tick, 1000);
        return () => clearInterval(interval);
    }, [period]);

    const radius = 20;
    const circumference = 2 * Math.PI * radius;
    const progress = secondsLeft / period;
    const offset = circumference * (1 - progress);
    const urgent = secondsLeft <= 5;

    return (
        <div className="otp-ring" title="Codes refresh every 30 seconds">
            <svg width="48" height="48" viewBox="0 0 48 48">
                <circle cx="24" cy="24" r={radius} fill="none" stroke="var(--border)" strokeWidth="4" />
                <circle
                    cx="24"
                    cy="24"
                    r={radius}
                    fill="none"
                    stroke={urgent ? "var(--verify)" : "var(--primary)"}
                    strokeWidth="4"
                    strokeLinecap="round"
                    strokeDasharray={circumference}
                    strokeDashoffset={offset}
                    transform="rotate(-90 24 24)"
                    style={{ transition: "stroke-dashoffset 1s linear, stroke .3s ease" }}
                />
            </svg>
            <span className="otp-ring-number mono">{secondsLeft}</span>
        </div>
    );
}

export default CodeCountdownRing;
